kind: pipeline
type: docker
name: hextech-gunblade

steps:
  - name: Run Program
    image: oven/bun:debian
    environment:
      FTP_URL:
        from_secret: FTP_URL
      FTP_USERNAME:
        from_secret: FTP_USERNAME
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
      NODE_ENV: production
    commands:
      - apt-get update && apt-get install -y wget apt-transport-https software-properties-common gnupg ca-certificates && rm -rf /var/lib/apt/lists/*
      - wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb
      - apt-get update && apt-get install -y dotnet-runtime-6.0
      - bun install
      - bun dev

  - name: discord notification files
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: >
        {{#success build.status}}
          Upload `{{build.number}}` succeeded.
        {{else}}
          Upload `{{build.number}}` failed.  
          Changes: {{commit.branch}} / {{commit.message}} from {{commit.author}}.  
          See: {{build.link}}
        {{/success}}